<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [
            [
                'name' => 'US Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'rate' => 1.0,
                'is_default' => true,
                'status' => true,
            ],
            [
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'rate' => 0.85,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'British Pound',
                'code' => 'GBP',
                'symbol' => '£',
                'rate' => 0.73,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Japanese Yen',
                'code' => 'JPY',
                'symbol' => '¥',
                'rate' => 110.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Canadian Dollar',
                'code' => 'CAD',
                'symbol' => 'C$',
                'rate' => 1.25,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Australian Dollar',
                'code' => 'AUD',
                'symbol' => 'A$',
                'rate' => 1.35,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Swiss Franc',
                'code' => 'CHF',
                'symbol' => 'Fr',
                'rate' => 0.92,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Chinese Yuan',
                'code' => 'CNY',
                'symbol' => '¥',
                'rate' => 6.45,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Swedish Krona',
                'code' => 'SEK',
                'symbol' => 'kr',
                'rate' => 8.60,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'New Zealand Dollar',
                'code' => 'NZD',
                'symbol' => 'NZ$',
                'rate' => 1.42,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Mexican Peso',
                'code' => 'MXN',
                'symbol' => '$',
                'rate' => 20.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Singapore Dollar',
                'code' => 'SGD',
                'symbol' => 'S$',
                'rate' => 1.35,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Hong Kong Dollar',
                'code' => 'HKD',
                'symbol' => 'HK$',
                'rate' => 7.78,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Norwegian Krone',
                'code' => 'NOK',
                'symbol' => 'kr',
                'rate' => 8.70,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'South Korean Won',
                'code' => 'KRW',
                'symbol' => '₩',
                'rate' => 1150.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Turkish Lira',
                'code' => 'TRY',
                'symbol' => '₺',
                'rate' => 8.60,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Russian Ruble',
                'code' => 'RUB',
                'symbol' => '₽',
                'rate' => 73.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Indian Rupee',
                'code' => 'INR',
                'symbol' => '₹',
                'rate' => 74.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Brazilian Real',
                'code' => 'BRL',
                'symbol' => 'R$',
                'rate' => 5.20,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'South African Rand',
                'code' => 'ZAR',
                'symbol' => 'R',
                'rate' => 14.50,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Azerbaijani Manat',
                'code' => 'AZN',
                'symbol' => '₼',
                'rate' => 1.70,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'UAE Dirham',
                'code' => 'AED',
                'symbol' => 'د.إ',
                'rate' => 3.67,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Argentine Peso',
                'code' => 'ARS',
                'symbol' => '$',
                'rate' => 97.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Bahraini Dinar',
                'code' => 'BHD',
                'symbol' => '.د.ب',
                'rate' => 0.376,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Thai Baht',
                'code' => 'THB',
                'symbol' => '฿',
                'rate' => 33.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Chilean Peso',
                'code' => 'CLP',
                'symbol' => '$',
                'rate' => 750.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Colombian Peso',
                'code' => 'COP',
                'symbol' => '$',
                'rate' => 3800.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Czech Koruna',
                'code' => 'CZK',
                'symbol' => 'Kč',
                'rate' => 21.5,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Danish Krone',
                'code' => 'DKK',
                'symbol' => 'kr',
                'rate' => 6.3,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Egyptian Pound',
                'code' => 'EGP',
                'symbol' => 'E£',
                'rate' => 15.7,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Hungarian Forint',
                'code' => 'HUF',
                'symbol' => 'Ft',
                'rate' => 300.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Indonesian Rupiah',
                'code' => 'IDR',
                'symbol' => 'Rp',
                'rate' => 14200.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Israeli New Shekel',
                'code' => 'ILS',
                'symbol' => '₪',
                'rate' => 3.25,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Kuwaiti Dinar',
                'code' => 'KWD',
                'symbol' => 'د.ك',
                'rate' => 0.30,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Malaysian Ringgit',
                'code' => 'MYR',
                'symbol' => 'RM',
                'rate' => 4.2,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Nigerian Naira',
                'code' => 'NGN',
                'symbol' => '₦',
                'rate' => 410.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Pakistani Rupee',
                'code' => 'PKR',
                'symbol' => '₨',
                'rate' => 163.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Peruvian Sol',
                'code' => 'PEN',
                'symbol' => 'S/',
                'rate' => 4.1,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Philippine Peso',
                'code' => 'PHP',
                'symbol' => '₱',
                'rate' => 50.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Polish Zloty',
                'code' => 'PLN',
                'symbol' => 'zł',
                'rate' => 3.9,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Qatari Riyal',
                'code' => 'QAR',
                'symbol' => 'ر.ق',
                'rate' => 3.64,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Romanian Leu',
                'code' => 'RON',
                'symbol' => 'lei',
                'rate' => 4.15,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Saudi Riyal',
                'code' => 'SAR',
                'symbol' => 'ر.س',
                'rate' => 3.75,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Taiwan Dollar',
                'code' => 'TWD',
                'symbol' => 'NT$',
                'rate' => 27.9,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Ukrainian Hryvnia',
                'code' => 'UAH',
                'symbol' => '₴',
                'rate' => 26.7,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Uruguayan Peso',
                'code' => 'UYU',
                'symbol' => '$U',
                'rate' => 43.5,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Vietnamese Dong',
                'code' => 'VND',
                'symbol' => '₫',
                'rate' => 23000.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Algerian Dinar',
                'code' => 'DZD',
                'symbol' => 'د.ج',
                'rate' => 135.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Angolan Kwanza',
                'code' => 'AOA',
                'symbol' => 'Kz',
                'rate' => 650.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Armenian Dram',
                'code' => 'AMD',
                'symbol' => '֏',
                'rate' => 490.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Bangladeshi Taka',
                'code' => 'BDT',
                'symbol' => '৳',
                'rate' => 85.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Belarusian Ruble',
                'code' => 'BYN',
                'symbol' => 'Br',
                'rate' => 2.5,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Bulgarian Lev',
                'code' => 'BGN',
                'symbol' => 'лв',
                'rate' => 1.65,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Costa Rican Colón',
                'code' => 'CRC',
                'symbol' => '₡',
                'rate' => 620.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Croatian Kuna',
                'code' => 'HRK',
                'symbol' => 'kn',
                'rate' => 6.3,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Dominican Peso',
                'code' => 'DOP',
                'symbol' => 'RD$',
                'rate' => 57.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Ethiopian Birr',
                'code' => 'ETB',
                'symbol' => 'Br',
                'rate' => 45.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Georgian Lari',
                'code' => 'GEL',
                'symbol' => '₾',
                'rate' => 3.1,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Ghanaian Cedi',
                'code' => 'GHS',
                'symbol' => '₵',
                'rate' => 6.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Icelandic Króna',
                'code' => 'ISK',
                'symbol' => 'kr',
                'rate' => 125.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Iraqi Dinar',
                'code' => 'IQD',
                'symbol' => 'ع.د',
                'rate' => 1460.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Jordanian Dinar',
                'code' => 'JOD',
                'symbol' => 'د.ا',
                'rate' => 0.71,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Kazakhstani Tenge',
                'code' => 'KZT',
                'symbol' => '₸',
                'rate' => 425.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Kenyan Shilling',
                'code' => 'KES',
                'symbol' => 'KSh',
                'rate' => 110.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Kyrgystani Som',
                'code' => 'KGS',
                'symbol' => 'с',
                'rate' => 84.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Lebanese Pound',
                'code' => 'LBP',
                'symbol' => 'ل.ل',
                'rate' => 1500.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Macedonian Denar',
                'code' => 'MKD',
                'symbol' => 'ден',
                'rate' => 52.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Mauritian Rupee',
                'code' => 'MUR',
                'symbol' => '₨',
                'rate' => 42.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Moldovan Leu',
                'code' => 'MDL',
                'symbol' => 'L',
                'rate' => 17.8,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Moroccan Dirham',
                'code' => 'MAD',
                'symbol' => 'د.م.',
                'rate' => 9.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Namibian Dollar',
                'code' => 'NAD',
                'symbol' => 'N$',
                'rate' => 14.5,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Nepalese Rupee',
                'code' => 'NPR',
                'symbol' => '₨',
                'rate' => 118.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Nicaraguan Córdoba',
                'code' => 'NIO',
                'symbol' => 'C$',
                'rate' => 35.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Omani Rial',
                'code' => 'OMR',
                'symbol' => 'ر.ع.',
                'rate' => 0.385,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Paraguayan Guarani',
                'code' => 'PYG',
                'symbol' => '₲',
                'rate' => 6900.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Serbian Dinar',
                'code' => 'RSD',
                'symbol' => 'дин.',
                'rate' => 100.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Sri Lankan Rupee',
                'code' => 'LKR',
                'symbol' => 'Rs',
                'rate' => 200.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Tajikistani Somoni',
                'code' => 'TJS',
                'symbol' => 'ЅМ',
                'rate' => 11.3,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Tanzanian Shilling',
                'code' => 'TZS',
                'symbol' => 'TSh',
                'rate' => 2300.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Tunisian Dinar',
                'code' => 'TND',
                'symbol' => 'د.ت',
                'rate' => 2.8,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Turkmenistan Manat',
                'code' => 'TMT',
                'symbol' => 'm',
                'rate' => 3.5,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Ugandan Shilling',
                'code' => 'UGX',
                'symbol' => 'USh',
                'rate' => 3500.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Uzbekistan Som',
                'code' => 'UZS',
                'symbol' => 'лв',
                'rate' => 10500.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Zambian Kwacha',
                'code' => 'ZMW',
                'symbol' => 'ZK',
                'rate' => 22.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Zimbabwean Dollar',
                'code' => 'ZWL',
                'symbol' => 'Z$',
                'rate' => 322.0,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Bitcoin',
                'code' => 'BTC',
                'symbol' => '₿',
                'rate' => 0.000023,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Ethereum',
                'code' => 'ETH',
                'symbol' => 'Ξ',
                'rate' => 0.00031,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Litecoin',
                'code' => 'LTC',
                'symbol' => 'Ł',
                'rate' => 0.0057,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Ripple',
                'code' => 'XRP',
                'symbol' => 'XRP',
                'rate' => 0.85,
                'is_default' => false,
                'status' => true,
            ],
            [
                'name' => 'Dogecoin',
                'code' => 'DOGE',
                'symbol' => 'Ð',
                'rate' => 4.5,
                'is_default' => false,
                'status' => true,
            ],
        ];

        foreach ($currencies as $currencyData) {
            Currency::firstOrCreate(
                ['code' => $currencyData['code']],
                $currencyData
            );
        }

        $this->command->info('Currency seeder has been run successfully.');
    }
}